#!/bin/bash

if [ -z "$1" ]; then
	echo "[*] use: $0 <start|stop> <LockFile>"
	exit 1
fi

case $1 in 
	start)
		touch $2
		#/etc/init.d/networking restart
                #/sbin/ifup vlan3110
                #/sbin/ifup vlan3120
                #/sbin/ifup vlan2175
                #/sbin/ifup vlan62
                #/sbin/ifup eth0
		exit $?
	;;
	stop)
		rm -f $2
		#killall ucarp
		#/sbin/ifdown vlan3110
		#/sbin/ifdown vlan3120
		#/sbin/ifdown vlan2175
		#/sbin/ifdown vlan62
		#/sbin/ifdown eth0
		exit $?
	;;
	check)	
		if [ -f "$2" ]; then 
			exit 0
			echo "UCARP Service $2 NOT Running"
		else
			exit 1
			echo "UCARP Service $2 is Running"
		fi
	;;
	*)
	echo "[*] WHAT? what do you want from me? (start|stop|check)"
	exit 1
	;;
esac

